stages:
- name: Deployment
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.mncbank.co.id:5000/be-main-template:v1.0.0
      pushRemote: true
      registry: docker.mncbank.co.id:5000
timeout: 60
notification: {}
